import { describe, expect, test } from "bun:test";
import { compileCarnapMarkdown } from "../src/worker/application/content/compiler";
import { renderCompiledContent } from "../src/worker/application/content/renderer";
import type {
  AnswerEnvelope,
  ExerciseManifestItem,
  NormalizedAnswer,
} from "../src/worker/domain/content";
import { AufbauProofFitchExerciseType } from "../src/worker/exercises/aufbau-proof-fitch/assessment";
import {
  AUFBAU_PROOF_FITCH_ANSWER_KIND,
  AUFBAU_PROOF_FITCH_SCHEMA_VERSION,
} from "../src/worker/exercises/aufbau-proof-fitch/types";
import { i18nFor } from "../src/worker/i18n";
import { passthroughTranslator } from "../src/worker/i18n/translator";
import { FITCH_THEORY_BLOCK } from "./helpers/fitch-theory";

/** Review text is resolved for a viewer, so a review needs a translator. */
const REVIEW_CONTEXT = {
  audience: "student",
  i18n: passthroughTranslator,
} as const;

/**
 * The Fitch source below translates (via `fitchToAuf`) to the `.auf`
 *   l1: $ a → b , a ⊢ a → b $ by ax []
 *   l2: $ a → b , a ⊢ a $ by ax []
 *   l3: $ a → b , a ⊢ b $ by imp_elim [l1, l2]
 * which the real `@aufbau` compiler turns into this MMB certificate against the
 * frozen `prop` theory + `mp` goal. The worker verifies it here against the same
 * frozen mm0 — the certificate is the sole graded input, never the Fitch text.
 */
const GOOD_MMB_BASE64 =
  "TU0wQgECAAAIAAAAGAAAACwAAABsAAAA+AUAAAAAAACwCgAAAAAAAAQAAAACAAAAMAEAAAIAAABIAQAAAgAAAGABAAACAAAAeAEAAAAAAQCQAQAAAgABAJgBAAABAAEAsAEAAAIAAADAAQAAAQAAANgBAAADAAAA6AEAAAIAAAAYAgAAAgAAADgCAAABAAAAWAIAAAMAAABoAgAAAgAAAJgCAAADAAAAuAIAAAIAAADoAgAAAQAAAAgDAAABAAAAGAMAAAQAAAAwAwAAAgAAAHADAAAEAAAAkAMAAAQAAADQAwAABAAAABAEAAACAAAAUAQAAAMAAABwBAAABAAAAJgEAAAFAAAA2AQAAAUAAAAgBQAABAAAAGgFAAAEAAAAoAUAAAIAAADYBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAIyMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAjJyAjZwAnIBcgI2cAIycgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAJyATI2cAIycgEAAAAAAAAAAAAAAAAAAAAAAAAAAAByATYyNnACMnIBAAAAAAAAAAAAAAAAAAFwAzIyAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAXADMnICNnADcgFyAjZwAzJyAQAAAAAAAAAAAAAAAAABAAAAAAAAAAFwA3IBMjZwAzJyAQAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABcANwBXAFMnIBcgJwBTJwBXIBcgIAAAAAAAAAAAAAAAEAAAAAAAAAAXADcAUycgFwBXIBMgAAAAAAAAAAAAAAAXADcAUyMjIAAAAAAAAAAAFwA3AFcAQyMgAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAFwA3AFMnICcAVyAXIDNnADcgJyAzZwAzJyAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABwA3AGMnAGcgE2cAIycgEAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAABwAnAHMnICcAdyAXIDNnACcgJyAzZwAzJyAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAIwMnICMHIBcgM2cAJyAnIDNnACMnIBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHACcAEycgJwAXIBcgM2cAJyAnIDNnACMnIBAAAAAAAAAAAAAAAAAAEAAAAAAAAAAHAHcAUycAZyAXIBAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAABwB3AFMnIBcgI2cAcycgIAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAABwB3AFMnIBMHICcgM2cAdwBTJwBnICcgMAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAABwB3AFcAUycgFyAnIENnAHcgFyAzZwBzIwcgNyBAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAABwB3AFcAUycgFyAnABcgNyBDZwB3IBcgQ2cAcycgMAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAcAdwBTJyAXICNnAHMnABcgJyAwAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAABwB3AFMnIBcgM2cAcycAFyAnIDAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAdwBXAGMDJyAXAGMnIBAEQCRAJFAkUCRQJFAkUCRQJFAkUCQgcSElECAEIVElIBUQIWUgFSAlECFhJSAlECAEIOElIBUQIWUgESUQIAQg0SUgFRAhYSFlIBAEIHEhJRAwBCFRJSAVEDFlIBUgJRAxYSUgJRAwBCDhJSAVEDFlIBElEDAEIXElIBUQVSAlEFElIBUgJRBVEFUQMAQg8SUgFRBVIBElEFUQMAQgoSElEFElEDAEILUQQSUQUSUQMAQh0SUgFRAxZSAlIDUQMWElICUQVSAVIDUQVRAwBCEhJSAVECFhJRBlIBUQZRAwBCHRJSAVEDFlICUgNRAhYSUgJRB1IBUgNRB1ECAEIbElIBUQIWUgJSA1ECFhJSAhFSAVIDEVECAEIdElIBUQIWUgJSA1ECFhJSAlEBUgFSA1EBUQIAQg4SUgFRBlEFUgFRBwBCEhJSAlEHFhJSAVEFUgJRBwBCGxJSAlEGUQVSA1EHFhJSAVEFUgJSAxFRBwBCIBJSA1IEEVEHFlIBUgNRBxYSUgFRBVICUQVSBFEHAEIhElIDUQcWUgFSBFEHFhJSAVEFUgJRBVIDUgRRAVEHAEIWElICUgNRAVEHFhJSAVEFUgJRBwBCFhJSAlIDUQFRBxYSUgFRBVIDUQcAhtUCElIBEVEGElEGUgNSBFEFUgRSA1EFUQNVCFIIUgVSBlIFUgZSBVIFUQVSBlIGUQVRA1ULUgRSA1IGUgpSBFIDUgZRBVEFUQNVB1IEUgRSBFEDVQRSA1IEUgNSBVIDUQVSDVEDVQdSE1INUg1SE1EDVQZSA1IEUgdVCFIDUgNSA1EDVQRSBVIGUgNSA1ITUgZSA1EFUQNVC1INUhNSG1INUhtRA1UFUgRSA1IDUhtSBFIDUgNRBVEFUQNVB1INUhtSIVINUiFRA1UFUgRSEVUEUgNSIFIDUQNVCVIEUgRSIFIDUiFSBlEDVQtSDVIhUgZSDVIGUQNVBVIEUgRSDVIGUg5SBFIGUQVRA1ULUgpSDlItUgpSLVEDVQVSBFIEUgNSBFIEUQVSA1EFUi1RA1UHUjNSLVItUjNRA1UGUgRSMlIEUQNVCVIDUhlVBFIyUgRSA1IDUjNSBlEDVQtSLVIzUgZSLVIGUQNVBVIKUi1SBlIKUgZRA1UFUglSClIGUglSBlEDVQVRBFJDUkNRA1UEUglSBlJDUkNSCVJDUQVSBlJDUQVRA1ULUgRSA1JDUkdSBFIDUkNRBVEFUQNVB1IEUhFVBFIDUkNSSlJDUgNRBVEDVQhSA1JPUgNRA1UKUkpST1IDUkpSA1EDVQVSBFIEUkpSA1JLUgZRA1ULUkdSS1IGUkdSBlEDVQVSRlJHUgZSRlIGUQNVBVIBUgFSAVECFVJGUgZSAVIBUkZSAVEHUgZSAVEHUQJVDVIIUgFSXBVSBVIGUgFSAVIFUgFRB1JfUQJVDVJjUl9SX1JjUQJVAlJeUl9SY1JeUmNRAlUBUgNSBFIHVQhSAlICUgJRAhVSBVIGUgJSAlIFUgJRB1IGUgJRB1ECVQ1SbVJuUm5SbVECVQJSBFICUm5VEFJuUm1SbVUDUgMSUgUSUQdVEFIFUgVSQxJSAVJeVRNSXlJjUmNVAwAAAAAAAAAAAwAAAAAAAABOYW1lAAAAAOgKAAAAAAAAVmFyTgAAAAAIDQAAAAAAAEh5cE4AAAAACA4AAAAAAAD4BQAAAAAAAMgOAAAAAAAA+gUAAAAAAADMDgAAAAAAAPwFAAAAAAAA0A4AAAAAAAD+BQAAAAAAANQOAAAAAAAAAAYAAAAAAADYDgAAAAAAAAIGAAAAAAAA3A4AAAAAAAAEBgAAAAAAAOMOAAAAAAAABgYAAAAAAADnDgAAAAAAAAgGAAAAAAAA7A4AAAAAAAAKBgAAAAAAAPAOAAAAAAAADAYAAAAAAADzDgAAAAAAABMGAAAAAAAA/A4AAAAAAAAoBgAAAAAAAAYPAAAAAAAANgYAAAAAAAAODwAAAAAAAEMGAAAAAAAAFQ8AAAAAAABKBgAAAAAAAB4PAAAAAAAAXwYAAAAAAAAoDwAAAAAAAG0GAAAAAAAAMA8AAAAAAACEBgAAAAAAADoPAAAAAAAAkwYAAAAAAABDDwAAAAAAAJ0GAAAAAAAATA8AAAAAAACoBgAAAAAAAFUPAAAAAAAAxQYAAAAAAABgDwAAAAAAANcGAAAAAAAAag8AAAAAAAD0BgAAAAAAAHMPAAAAAAAADwcAAAAAAAB9DwAAAAAAACwHAAAAAAAAhw8AAAAAAAA6BwAAAAAAAIoPAAAAAAAATAcAAAAAAACPDwAAAAAAAGcHAAAAAAAAmQ8AAAAAAACHBwAAAAAAAKIPAAAAAAAAqAcAAAAAAACsDwAAAAAAAL4HAAAAAAAAtw8AAAAAAADUBwAAAAAAAMIPAAAAAAAAyA8AAAAAAADoDwAAAAAAAAgQAAAAAAAAKBAAAAAAAABIEAAAAAAAAFAQAAAAAAAAcBAAAAAAAACIEAAAAAAAAKgQAAAAAAAAwBAAAAAAAADoEAAAAAAAAAgRAAAAAAAAKBEAAAAAAABAEQAAAAAAAGgRAAAAAAAAiBEAAAAAAACwEQAAAAAAANARAAAAAAAA6BEAAAAAAAAAEgAAAAAAADgSAAAAAAAAWBIAAAAAAACIEgAAAAAAALgSAAAAAAAA6BIAAAAAAAAIEwAAAAAAADATAAAAAAAAYBMAAAAAAACgEwAAAAAAAOATAAAAAAAAEBQAAAAAAABAFAAAAAAAAGAUAAAAAAAAaBQAAAAAAACIFAAAAAAAAKAUAAAAAAAAwBQAAAAAAADIFAAAAAAAAOgUAAAAAAAAABUAAAAAAAAIFQAAAAAAABAVAAAAAAAAGBUAAAAAAAAgFQAAAAAAAEAVAAAAAAAAWBUAAAAAAAB4FQAAAAAAAJgVAAAAAAAAuBUAAAAAAADAFQAAAAAAANgVAAAAAAAA8BUAAAAAAAAQFgAAAAAAADAWAAAAAAAASBYAAAAAAABgFgAAAAAAAHdmZgBjdHgAaW1wAGFuZABpZmYAY3R4X2VxAGVtcABqb2luAGh5cABuZABpZmZfcmVmbABpZmZfdHJhbnMAaWZmX3N5bQBpZmZfbXAAY3R4X3JlZmwAY3R4X3RyYW5zAGN0eF9zeW0AY3R4X2Fzc29jAGN0eF9jb21tAGN0eF9pZGVtAGN0eF91bml0AGpvaW5fY29uZ3IAaHlwX2NvbmdyAG5kX2NvbmdyAGltcF9jb25ncgBhbmRfY29uZ3IAYXgAcmVpdABpbXBfaW50cm8AaW1wX2VsaW0AYW5kX2ludHJvAGFuZF9lbGltX2wAYW5kX2VsaW1fcgBtcAAAAAACAAAAAAAAAOAPAAAAAAAA4g8AAAAAAABhAGIAAAAAAAIAAAAAAAAAABAAAAAAAAACEAAAAAAAAGEAYgAAAAAAAgAAAAAAAAAgEAAAAAAAACIQAAAAAAAAYQBiAAAAAAACAAAAAAAAAEAQAAAAAAAAQhAAAAAAAABnAGgAAAAAAAAAAAAAAAAAAgAAAAAAAABoEAAAAAAAAGoQAAAAAAAAZwBoAAAAAAABAAAAAAAAAIAQAAAAAAAAYQAAAAAAAAACAAAAAAAAAKAQAAAAAAAAohAAAAAAAABnAGEAAAAAAAEAAAAAAAAAuBAAAAAAAABhAAAAAAAAAAMAAAAAAAAA4BAAAAAAAADiEAAAAAAAAOQQAAAAAAAAYQBiAGMAAAACAAAAAAAAAAARAAAAAAAAAhEAAAAAAABhAGIAAAAAAAIAAAAAAAAAIBEAAAAAAAAiEQAAAAAAAGEAYgAAAAAAAQAAAAAAAAA4EQAAAAAAAGcAAAAAAAAAAwAAAAAAAABgEQAAAAAAAGIRAAAAAAAAZBEAAAAAAABnAGgAaQAAAAIAAAAAAAAAgBEAAAAAAACCEQAAAAAAAGcAaAAAAAAAAwAAAAAAAACoEQAAAAAAAKoRAAAAAAAArBEAAAAAAABnAGgAaQAAAAIAAAAAAAAAyBEAAAAAAADKEQAAAAAAAGcAaAAAAAAAAQAAAAAAAADgEQAAAAAAAGcAAAAAAAAAAQAAAAAAAAD4EQAAAAAAAGcAAAAAAAAABAAAAAAAAAAoEgAAAAAAACsSAAAAAAAALhIAAAAAAAAxEgAAAAAAAGcxAGcyAGgxAGgyAAAAAAACAAAAAAAAAFASAAAAAAAAUhIAAAAAAABhAGIAAAAAAAQAAAAAAAAAgBIAAAAAAACCEgAAAAAAAIQSAAAAAAAAhhIAAAAAAABnAGgAYQBiAAQAAAAAAAAAsBIAAAAAAACyEgAAAAAAALQSAAAAAAAAthIAAAAAAABhAGIAYwBkAAQAAAAAAAAA4BIAAAAAAADiEgAAAAAAAOQSAAAAAAAA5hIAAAAAAABhAGIAYwBkAAIAAAAAAAAAABMAAAAAAAACEwAAAAAAAGcAYQAAAAAAAwAAAAAAAAAoEwAAAAAAACoTAAAAAAAALBMAAAAAAABnAGgAYQAAAAQAAAAAAAAAWBMAAAAAAABaEwAAAAAAAFwTAAAAAAAAXhMAAAAAAABnAGgAYQBiAAUAAAAAAAAAkBMAAAAAAACSEwAAAAAAAJQTAAAAAAAAlhMAAAAAAACYEwAAAAAAAGcAaABpAGEAYgAAAAAAAAAFAAAAAAAAANATAAAAAAAA0hMAAAAAAADUEwAAAAAAANYTAAAAAAAA2BMAAAAAAABnAGgAaQBhAGIAAAAAAAAABAAAAAAAAAAIFAAAAAAAAAoUAAAAAAAADBQAAAAAAAAOFAAAAAAAAGcAaABhAGIABAAAAAAAAAA4FAAAAAAAADoUAAAAAAAAPBQAAAAAAAA+FAAAAAAAAGcAaABhAGIAAgAAAAAAAABYFAAAAAAAAFoUAAAAAAAAYQBiAAAAAAAAAAAAAAAAAAIAAAAAAAAAgBQAAAAAAACDFAAAAAAAACMxACMyAAAAAQAAAAAAAACYFAAAAAAAACMxAAAAAAAAAgAAAAAAAAC4FAAAAAAAALsUAAAAAAAAIzEAIzIAAAAAAAAAAAAAAAIAAAAAAAAA4BQAAAAAAADjFAAAAAAAACMxACMyAAAAAQAAAAAAAAD4FAAAAAAAACMxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAADgVAAAAAAAAOxUAAAAAAAAjMQAjMgAAAAEAAAAAAAAAUBUAAAAAAAAjMQAAAAAAAAIAAAAAAAAAcBUAAAAAAABzFQAAAAAAACMxACMyAAAAAgAAAAAAAACQFQAAAAAAAJMVAAAAAAAAIzEAIzIAAAACAAAAAAAAALAVAAAAAAAAsxUAAAAAAAAjMQAjMgAAAAAAAAAAAAAAAQAAAAAAAADQFQAAAAAAACMxAAAAAAAAAQAAAAAAAADoFQAAAAAAACMxAAAAAAAAAgAAAAAAAAAIFgAAAAAAAAsWAAAAAAAAIzEAIzIAAAACAAAAAAAAACgWAAAAAAAAKxYAAAAAAAAjMQAjMgAAAAEAAAAAAAAAQBYAAAAAAAAjMQAAAAAAAAEAAAAAAAAAWBYAAAAAAAAjMQAAAAAAAAAAAAAAAAAA";

const SOURCE = `${FITCH_THEORY_BLOCK}

:::aufbau-proof-fitch{theory="prop" id="mp1" points="2"}
Prove modus ponens.

theorem mp (a b: wff): $ (a → b) , a ⊢ b $
----
a → b   :ax
a       :ax
b       :imp_elim 1 2
:::`;

const FITCH_TEXT = [
  "a → b   :ax",
  "a       :ax",
  "b       :imp_elim 1 2",
].join("\n");

const type = new AufbauProofFitchExerciseType();

async function declarationFor(): Promise<ExerciseManifestItem> {
  const compiled = await compileCarnapMarkdown(SOURCE);
  if (!compiled.ok) {
    throw new Error(
      `compile failed: ${compiled.diagnostics.map((d) => d.code).join(", ")}`,
    );
  }
  const item = compiled.artifact.manifest.find((entry) => entry.id === "mp1");
  if (item === undefined) {
    throw new Error("no mp1 exercise");
  }
  return item;
}

function normalizedAnswer(mmb: string): NormalizedAnswer {
  return {
    data: {
      fitchText: FITCH_TEXT,
      mmb,
      proofText: "",
    } as unknown as NormalizedAnswer["data"],
    kind: AUFBAU_PROOF_FITCH_ANSWER_KIND,
    schemaVersion: AUFBAU_PROOF_FITCH_SCHEMA_VERSION,
  };
}

function envelope(data: unknown): AnswerEnvelope {
  return {
    data: data as AnswerEnvelope["data"],
    kind: AUFBAU_PROOF_FITCH_ANSWER_KIND,
    schemaVersion: AUFBAU_PROOF_FITCH_SCHEMA_VERSION,
  };
}

describe("aufbau-proof-fitch assessment", () => {
  test("a verifying certificate for the translated proof scores full marks", async () => {
    const declaration = await declarationFor();
    const evaluation = await type.evaluate(
      normalizedAnswer(GOOD_MMB_BASE64),
      declaration,
      { now: "1970-01-01T00:00:00.000Z" },
    );
    expect(evaluation.status).toBe("correct");
    expect(evaluation.awardedScore).toBe(2);
  });

  test("a certificate that does not verify scores zero", async () => {
    const declaration = await declarationFor();
    // Valid base64 but not a real MMB — the verifier errors, no credit.
    const evaluation = await type.evaluate(
      normalizedAnswer(btoa("not an mmb")),
      declaration,
      { now: "1970-01-01T00:00:00.000Z" },
    );
    expect(evaluation.awardedScore).toBe(0);
    expect(
      evaluation.status === "incorrect" || evaluation.status === "error",
    ).toBe(true);
  });

  test("a wrong answer kind is rejected", async () => {
    const declaration = await declarationFor();
    const result = type.normalizeAnswer(
      {
        data: { fitchText: "", mmb: "", proofText: "" },
        kind: "something-else",
        schemaVersion: AUFBAU_PROOF_FITCH_SCHEMA_VERSION,
      },
      declaration,
    );
    expect(result.ok).toBe(false);
  });

  test("malformed answer data is rejected", async () => {
    const declaration = await declarationFor();
    const result = type.normalizeAnswer(
      envelope({ mmb: "not-base-64!!!" }),
      declaration,
    );
    expect(result.ok).toBe(false);
  });

  test("review renders the submitted Fitch source read-only", async () => {
    const declaration = await declarationFor();
    const review = type.reviewAnswer(
      normalizedAnswer(GOOD_MMB_BASE64),
      declaration,
      REVIEW_CONTEXT,
    );
    expect(review.summary).toBe("Aufbau Fitch proof");
    expect(review.details?.[0]).toEqual({ label: "Goal", value: "mp" });
    expect(review.elementHtml).toContain("data-review");
    expect(review.elementHtml).toContain("imp_elim 1 2");
    // The bundle loads on review pages so the element upgrades to a read-only
    // CodeMirror with scope-lines; the assumption rule seeds that scope walk.
    expect(review.elementHtml).toContain(
      "/assets/components/carnap-aufbau-proof-fitch-v1.js",
    );
    expect(review.elementHtml).toContain('data-assumption-rule="ax"');
  });
});

describe("aufbau-proof-fitch rendering", () => {
  test("the compiled exercise renders its element with the starter source", async () => {
    const compiled = await compileCarnapMarkdown(SOURCE);
    expect(compiled.ok).toBe(true);
    if (!compiled.ok) {
      return;
    }
    const html = renderCompiledContent(compiled.artifact, i18nFor("en"));
    expect(html).toContain("<carnap-aufbau-proof-fitch ");
    expect(html).toContain("Prove modus ponens.");
    expect(html).toContain("imp_elim 1 2");
  });
});
