import { flattenProofTree } from "../../src/worker/exercises/aufbau-proof-tree/flatten";
import type { ProofTreeNode } from "../../src/worker/exercises/aufbau-proof-tree/types";
import { GENTZEN_CASES } from "./gentzen-cases";
import { GENTZEN_THEORY_MM0 } from "./gentzen-theory";

/**
 * A second Gentzen-LK demo lesson, built to exercise the **pre-populated tree**
 * feature (`starterTree`, authored as a `----` starter body). Every exercise here
 * ships with a starter proof so you can see how the tree editor seeds — and how
 * ProofML *renders* — trees of rising size, up to the double-`cut` permutation
 * proof. Two flavours are shown:
 *
 *   - **Worked examples** whose starter is the *complete* engine-verified proof
 *     (the student opens straight to a ✓ and studies the finished tree).
 *   - **A scaffold** whose starter is the same proof with one node's premises
 *     pruned away, so the student finishes it by adding the missing leaves.
 *
 * The starter bodies are generated by `flattenProofTree` from the very same
 * `GENTZEN_CASES` that `scripts/gentzen-verify.ts` compiles + verifies against the
 * real engine, so the worked ones are guaranteed to check and can never drift.
 * Shared by the authoring compile-check test and the seed script
 * (`scripts/seed-gentzen-starter-demo.ts`).
 */

/** The engine-verified case with `name` starting with `prefix`. */
function caseByName(prefix: string) {
  const found = GENTZEN_CASES.find((testCase) =>
    testCase.name.startsWith(prefix),
  );
  if (found === undefined) {
    throw new Error(`no Gentzen case named '${prefix}'`);
  }
  return found;
}

/** The `theorem …: $ … $` header line for a directive (no trailing `;`). */
function headerOf(prefix: string): string {
  return caseByName(prefix).theoremDecl.replace(/;\s*$/, "");
}

/** The starter body — the `.auf` lines a tree flattens to, minus the header. */
function starterBodyOf(tree: ProofTreeNode, goalName: string): string {
  const body = flattenProofTree(tree, goalName).proofText.split(
    "\n----\n",
  )[1];
  if (body === undefined) {
    throw new Error(`could not flatten a starter body for '${goalName}'`);
  }
  return body;
}

/** Clone `node`, emptying the premises of every node matching `prune`. */
function pruningPremises(
  node: ProofTreeNode,
  prune: (node: ProofTreeNode) => boolean,
): ProofTreeNode {
  return {
    ...node,
    premises: prune(node)
      ? []
      : node.premises.map((child) => pruningPremises(child, prune)),
  };
}

const forallToExists = caseByName("forall_to_exists");
const existsMono = caseByName("exists_mono");
const existsOrDistrib = caseByName("exists_or_distrib");
const permute = caseByName("forall_exists_permute_mono");

// The scaffold: `exists_mono` with the `imp_left` node's two `ax` leaves removed,
// so the student adds `P x ==> P x` and `Q x ==> Q x` back to finish the proof.
const existsMonoScaffold = pruningPremises(
  existsMono.tree,
  (node) => node.rule === "imp_left",
);

export const GENTZEN_STARTER_DEMO_SOURCE = `# Pre-populated sequent proofs — Gentzen's *LK*

Every proof below opens **already populated** in the tree editor. The classical
sequent calculus **LK** is the same one from the earlier lesson: a sequent is
\`Γ ==> Δ\`, contraction and exchange are free, and the only structural rules are
\`ax\`, \`weak_left\` / \`weak_right\`, and \`cut\`. What is new here is that the
instructor can *seed the tree* — as a **worked example** to study, or as a
**scaffold** with a step or two left for you to fill in.

:::aufbau-mm0{name="gentzen"}
${GENTZEN_THEORY_MM0}
:::

## 1. A worked example

This one arrives finished: \`∀ x P x ==> ∃ y P y\` by \`all_left\` then \`ex_right\`
over an \`ax\` leaf. Open it and it already shows a ✓ — read the completed tree
from the root sequent downward, then press **Check** to confirm it verifies.

:::aufbau-proof-tree{theory="gentzen" id="starter_forall_to_exists" points="1"}
A completed proof — study how \`all_left\` reads its witness off the sequent.

${headerOf("forall_to_exists")}
----
${starterBodyOf(forallToExists.tree, forallToExists.goalName)}
:::

## 2. A scaffold — finish the proof

Here the outer chain is given, but the \`imp_left\` step at the top has **no
premises yet**. Select that node and *Add premise* twice to supply the two
identity leaves \`P x ==> P x\` and \`Q x ==> Q x\`; the ✓ appears once both are in.

:::aufbau-proof-tree{theory="gentzen" id="starter_exists_mono" points="3"}
The \`imp_left\` node is waiting for its two \`ax\` leaves — add them to close the proof.

${headerOf("exists_mono")}
----
${starterBodyOf(existsMonoScaffold, existsMono.goalName)}
:::

## 3. A branching worked example

\`∃\` distributes over \`∨\`. The \`or_left\` rule grows **two** subtrees — one
assuming \`P x\`, one assuming \`Q x\` — so this is a good look at how the editor lays
out a tree that forks. It arrives complete.

:::aufbau-proof-tree{theory="gentzen" id="starter_exists_or_distrib" points="4"}
A completed branching proof — note the two subtrees under \`or_left\`.

${headerOf("exists_or_distrib")}
----
${starterBodyOf(existsOrDistrib.tree, existsOrDistrib.goalName)}
:::

## 4. A large worked proof

The showcase: permuting a \`∀∃\` prefix past a monotone matrix, \`∀ u ∃ v (P u ∧ Q v)
==> ∃ y ∀ x (P x ∧ Q y)\`. It uses **two** \`cut\`s and threads \`and_left\` /
\`and_right\`, \`weak_left\`, and every quantifier rule through a deep tree — the
stress test for how ProofML renders something big. It arrives complete.

:::aufbau-proof-tree{theory="gentzen" id="starter_permute_mono" points="6"}
A completed deep proof (two cuts) — scroll the tree and see how the layout holds up.

${headerOf("forall_exists_permute_mono")}
----
${starterBodyOf(permute.tree, permute.goalName)}
:::`;
